name: build
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
          POSTGRES_USER: ergol
          POSTGRES_PASSWORD: ergol
          POSTGRES_DB: ergol
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Add second database to avoid collisions
      run: psql 'postgres://ergol:ergol@localhost:5432' -c 'CREATE DATABASE "ergol2";'
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'
    - name: Build
      run: cargo build --features with-rocket --verbose
    - name: Run book tests
      run: cd book && mdbook test -L ../target/debug/deps
    - name: Run tests
      run: cargo test --verbose -- --test-threads=1
    - name: Run examples
      run: for i in examples/*; do if [ -f "$i/Cargo.toml" ]; then cd $i; cargo run; cd ../..; fi; done
    - name: Run mdBook
      run: cd book && mdbook build
    - name: Deploy mdBook
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: ergol-rs/ergol-rs.github.io
        publish_branch: main
        publish_dir: ./book/book
