name: build
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
          POSTGRES_USER: ergol
          POSTGRES_PASSWORD: ergol
          POSTGRES_DB: ergol
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --test-threads=1
    - name: Run examples
      run: cargo run --bin one-to-one
      run: cargo run --bin many-to-one
      run: cargo run --bin many-to-many
      run: cargo run --bin many-to-many-extra
      run: cargo run --bin query
      run: cargo run --bin rocket --features with-rocket
